# Generated by Django 3.1 on 2020-11-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='alum_group_public_name',
            new_name='group_public_name',
        ),
    ]
