# Generated by Django 3.1 on 2020-11-04 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20201104_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='alum_in_group',
        ),
        migrations.AddField(
            model_name='profile',
            name='alum_in_group',
            field=models.ManyToManyField(related_name='alum_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
