# Generated by Django 3.1 on 2020-11-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_group_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='group_public_name',
        ),
    ]
