# Generated by Django 3.1 on 2020-11-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=50, unique=True, verbose_name='A word'),
        ),
    ]
