# Generated by Django 3.1 on 2020-11-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201105_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='type',
            field=models.CharField(choices=[('animal', 'animal'), ('color', 'color'), ('adjective', 'adjective')], db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='A word'),
        ),
    ]
