# Generated by Django 3.1 on 2020-11-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201105_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group_picture',
            field=models.ImageField(null=True, upload_to='media/group_pics/'),
        ),
    ]
