# Generated by Django 3.1 on 2020-11-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_profile_center_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Question order inside the quiz'),
            preserve_default=False,
        ),
    ]
