# Generated by Django 3.1 on 2020-11-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_question_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='order',
            new_name='question_order',
        ),
    ]
