# Generated by Django 3.1 on 2020-11-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201125_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='label',
            field=models.CharField(default='a', max_length=10, verbose_name='Label'),
            preserve_default=False,
        ),
    ]
