# Generated by Django 3.1 on 2020-11-30 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_answer_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alum_answered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main.answer')),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alum_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to='main.question')),
            ],
        ),
    ]
