# Generated by Django 3.1 on 2020-12-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201201_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='doc_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
