# Generated by Django 3.1 on 2020-12-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201201_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenquiz',
            name='score',
        ),
        migrations.AddField(
            model_name='quiz',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='assigned_score',
            field=models.IntegerField(default=0, help_text='Score given by tutor. Can be different and supersedes the former.'),
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='computed_score',
            field=models.IntegerField(default=0, help_text='Score automatically calculated when the quiz is finished'),
        ),
    ]
