# Generated by Django 3.1 on 2020-12-28 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_auto_20201224_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_score', models.IntegerField(default=0, help_text='Score automatically calculated when the quiz is finished')),
                ('assigned_score', models.IntegerField(default=0, help_text='Score given by tutor. Can be different and supersedes the former.')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('first_run', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='main.quiz')),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TakenQuiz',
        ),
    ]
