# Generated by Django 3.1 on 2020-12-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201228_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizrun',
            name='first_run',
        ),
        migrations.AddField(
            model_name='quizrun',
            name='run_number',
            field=models.IntegerField(default=1),
        ),
    ]
