# Generated by Django 3.1 on 2020-12-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20201228_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrun',
            name='date_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
