# Generated by Django 3.1 on 2020-12-28 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_quizrun_date_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizRunAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_answer', to='main.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_question', to='main.question')),
                ('quizrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.quizrun')),
            ],
        ),
    ]
