# Generated by Django 3.1 on 2020-12-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_quizrunanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrunanswers',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
