# Generated by Django 3.1 on 2020-12-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_quizrunanswers_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizrun',
            name='assigned_score',
        ),
        migrations.RemoveField(
            model_name='quizrun',
            name='computed_score',
        ),
        migrations.AddField(
            model_name='quizrun',
            name='questions_number',
            field=models.IntegerField(default=0, help_text='Number of questions when the quiz was finished'),
        ),
        migrations.AddField(
            model_name='quizrun',
            name='questions_right',
            field=models.IntegerField(default=0, help_text='Number of correctly answered questions in the run'),
        ),
    ]
