# Generated by Django 3.1 on 2021-01-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20201229_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='groupanswer',
            name='group',
        ),
        migrations.RemoveField(
            model_name='quizsolution',
            name='alum_answered',
        ),
        migrations.RemoveField(
            model_name='quizsolution',
            name='answered_by',
        ),
        migrations.RemoveField(
            model_name='quizsolution',
            name='question',
        ),
        migrations.DeleteModel(
            name='AssignedQuiz',
        ),
        migrations.DeleteModel(
            name='GroupAnswer',
        ),
        migrations.DeleteModel(
            name='QuizSolution',
        ),
    ]
