# Generated by Django 3.1 on 2021-01-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_profile_group_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='type',
            field=models.IntegerField(choices=[(0, 'test'), (1, 'material'), (2, 'poll')], default=0),
            preserve_default=False,
        ),
    ]
