# Generated by Django 3.1 on 2021-01-19 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='requisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allows', to='main.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='type',
            field=models.IntegerField(choices=[(0, 'Test'), (1, 'Material'), (2, 'Enquesta')]),
        ),
    ]
