# Generated by Django 3.1 on 2021-02-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210119_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrunanswers',
            name='uploaded_material',
            field=models.FileField(null=True, upload_to='media/uploaded/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_order',
            field=models.IntegerField(default=1, verbose_name='Question order inside the quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='type',
            field=models.IntegerField(choices=[(0, 'Test'), (1, 'Material'), (2, 'Enquesta'), (3, 'Pujar fitxer')]),
        ),
    ]
