# Generated by Django 3.1 on 2021-02-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210201_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizrunanswers',
            name='uploaded_material',
            field=models.FileField(blank=True, null=True, upload_to='media/uploaded/'),
        ),
    ]
