# Generated by Django 3.1 on 2021-02-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210201_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_picture',
            field=models.ImageField(null=True, upload_to='media/question_pics/'),
        ),
    ]
