# Generated by Django 3.1 on 2021-04-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_quiz_html_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=2),
        ),
    ]
