# Generated by Django 3.1 on 2021-09-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210407_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='n_students_in_group',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='type',
            field=models.IntegerField(choices=[(0, 'Test'), (1, 'Material'), (2, 'Enquesta'), (3, 'Pujar fitxer'), (4, 'Enquesta professorat')]),
        ),
    ]
