# Generated by Django 3.1 on 2021-04-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210407_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='professor_poll',
            field=models.BooleanField(default=False),
        ),
    ]
