# Generated by Django 3.1 on 2022-02-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_educationcenter_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcenter',
            name='hashtag',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
