# Generated by Django 3.1 on 2022-02-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20220225_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group_hashtag',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
