# Generated by Django 3.1 on 2022-02-24 11:18

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_educationcenter_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='campaign',
            field=models.ForeignKey(blank=True, default=main.models.get_current_active_campaign, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='main.campaign'),
        ),
        migrations.AlterField(
            model_name='educationcenter',
            name='campaign',
            field=models.ForeignKey(blank=True, default=main.models.get_current_active_campaign, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_centers', to='main.campaign'),
        ),
    ]
