# Generated by Django 3.1 on 2022-02-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_profile_campaign'),
        ('main', '0040_profile_group_hashtag'),
    ]

    operations = [
    ]
