# Generated by Django 3.1 on 2022-07-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_merge_20220228_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_uuid', models.CharField(blank=True, max_length=36, unique=True)),
                ('observation_date', models.DateTimeField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('private_webmap_layer', models.CharField(blank=True, max_length=255)),
                ('photo_url', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField()),
                ('center_hashtag', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
