# Generated by Django 3.1 on 2022-07-21 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_breedingsites'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedingsites',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeding_sites', to='main.campaign'),
        ),
    ]
