# Generated by Django 3.1 on 2022-07-25 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0045_breedingsites_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_bracket', models.CharField(blank=True, max_length=36)),
                ('format', models.CharField(blank=True, max_length=100)),
                ('award', models.CharField(blank=True, max_length=100)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center_awards', to='main.educationcenter')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_awards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
