# Generated by Django 3.1 on 2022-11-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sequence in which the quizzes are meant to be taken'),
        ),
    ]
