# Generated by Django 3.1 on 2023-01-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_quiz_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='order',
            new_name='seq',
        ),
    ]
