# Generated by Django 3.1 on 2023-01-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20230110_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='html_header_groups',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='html_header_teachers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
