# Generated by Django 3.1 on 2023-01-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20230111_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrun',
            name='finishing_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
