# Generated by Django 3.1 on 2023-01-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_quizrun_finishing_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrunanswers',
            name='open_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='type',
            field=models.IntegerField(choices=[(0, 'Test'), (1, 'Material'), (2, 'Enquesta'), (3, 'Pujar fitxer'), (4, 'Enquesta professorat'), (5, 'Resposta oberta')]),
        ),
    ]
