# Generated by Django 3.1 on 2023-01-25 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0051_auto_20230124_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('corrected_quizrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='main.quizrun')),
                ('corrector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrected_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
