# Generated by Django 3.1 on 2023-01-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20230125_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group_class',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
