# Generated by Django 3.1 on 2023-01-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_profile_group_class_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teacher_password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
