# Generated by Django 3.1 on 2024-01-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20230323_1120'),
    ]

    operations = [
        migrations.RunSQL('CREATE UNIQUE INDEX if not exists main_quizrun_notnull_idx ON main_quizrun (quiz_id, taken_by_id) WHERE date_finished IS NULL; CREATE UNIQUE INDEX if not exists main_quizrun_null_idx ON main_quizrun (quiz_id, taken_by_id, date_finished) WHERE date_finished IS NOT NULL;')
    ]
