# Generated by Django 3.1 on 2024-01-11 15:27

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_single_inprogress_quizrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrunanswers',
            name='authorize_material_public_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='educationcenter',
            name='campaign',
            field=models.ForeignKey(blank=True, default=main.models.get_current_active_campaign, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_centers', to='main.campaign'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='campaign',
            field=models.ForeignKey(blank=True, default=main.models.get_current_active_campaign, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='main.campaign'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='campaign',
            field=models.ForeignKey(blank=True, default=main.models.get_current_active_campaign, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='main.campaign'),
        ),
    ]
