# Generated by Django 3.1 on 2024-01-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_reset_answer_sequence'),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT setval('main_question_id_seq', (select max(id)+1 from main_question), true);"
        )
    ]
