# Generated by Django 3.1 on 2024-10-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_centermapdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapAwardData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_bracket', models.CharField(max_length=500)),
                ('format', models.CharField(max_length=500)),
                ('award', models.CharField(max_length=500)),
                ('center_hashtag', models.CharField(max_length=100)),
                ('center_name', models.CharField(max_length=500)),
                ('group_hashtag', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=500)),
            ],
        ),
    ]
