# Generated by Django 3.1 on 2025-01-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_mapawarddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consent_form_visited',
            field=models.BooleanField(default=False),
        ),
    ]
