# Generated by Django 3.1 on 2025-01-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_profile_consent_form_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='auth_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
