# Generated by Django 3.1 on 2025-03-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20250109_1053'),
        ('main', '0068_auto_20250115_0905'),
    ]

    operations = [
    ]
