# Generated by Django 3.1 on 2026-01-28 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_remove_profile_auth_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('consent_datause', models.BooleanField(default=False)),
                ('consent_datause_tutor', models.BooleanField(default=False)),
                ('consent_datashare', models.BooleanField(default=False)),
                ('consent_datashare_tutor', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_fullconsent', to='main.profile')),
            ],
        ),
    ]
