# Be aware of changing the name since there are dependnecies
name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  # See: https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_call:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # With no caching at all the entire ci process takes 4m 30s to complete!
  test:
    name: Test application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          # Same as docker-compose
          build-args: |
            BUILD_ENVIRONMENT=local
          # Same as Dockerfile service image name.
          tags: aula_local
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Django Tests
        # Need to run as root because we are writing the results into the shared volume.
        run: docker compose -f docker-compose-local.yml run -u root --rm django python manage.py test

      - name: Tear down the Stack
        run: docker-compose -f docker-compose-local.yml down